# Generated by Django 2.2.7 on 2019-12-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DoacaoAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('cidade', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
                ('produto', models.CharField(choices=[('MV', 'Moveis'), ('ED', 'Eletronico')], max_length=2)),
                ('imagem', models.ImageField(upload_to='')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoacaoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('cidade', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
                ('produto', models.CharField(choices=[('MV', 'Moveis'), ('ED', 'Eletronico')], max_length=2)),
                ('imagem', models.ImageField(upload_to='')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
    ]
