# Generated by Django 3.0 on 2019-12-09 01:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trash_way', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lixo',
            new_name='Produto',
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produto',
        ),
    ]
